function [fitresult, gof, times, rate] = fitRateData(x,y, numToFit)
    [times, rate] = getRateData(x,y);
    
    if ~exist('numToFit')
        numToFit = length(x)-1;
    end
    
    [fitresult, gof] = createFit(times(1:numToFit), rate(1:numToFit));
    

function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Jul-2015 11:15:29


%% Fit: 'untitled fit 1'.


% Set up fittype and options.
ft = fittype( 'a/(x+c)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
% opts.StartPoint = [0.485375648722841 0.8002804688888 0.141886338627215];
opts.StartPoint = [450 -0.68];
% opts.Lower = [100 1000 -3];
% opts.Upper = [1000 3000 3];
% opts.StartPoint = [500.2 1732.93	-0.4];
% opts.Lower = [0 0.0001];
% opts.Upper = [10000 0.001];

% Fit model to data.
[fitresult, gof] = fit( x, y, ft, opts );

