function fitViewData(a)
    x = a(:,1);
    y= a(:,2);
    [fitresult, gof] = createFit(x, y);
    crossesat = exp((4000-fitresult.b)/fitresult.a) - 0.1;
    fprintf('a\tb\t2\t8\t30\t90\tcrosses 4000\n')
    fprintf('%.2f\t%.2f\t%.0f\t%.0f\t%.0f\t%.0f\t%.0f\n',fitresult.a,fitresult.b, feval(fitresult,2), feval(fitresult,8), feval(fitresult,30), feval(fitresult,90), crossesat)

    function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Jul-2015 11:21:02


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*log(x+0.1)+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.445586200710899 0.646313010111265];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'best' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on


